include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_final_locals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - valid_regexps
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - require_trailing_commas
    - prefer_relative_imports
    - directives_ordering

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
